### ISSUE TITLE
Apps Not loading on Parse Dashboard 

### ISSUE THREAD

**Issue by jamccomb92** [hopetambala/puente-node-cloudcode#24]
### Description
_Describe your issue here._

When running the application locally and attempting to view the app on the parse dashboard, it states "You don't have any apps"
 
### Environment
- version of puente-node-cloudcode? 1.2
- which browser and its version? Safari 12.1.1
- versions of the following (if known and/or applicable)
  - node.js: 8.16
  - parse-server: 2.0.3

### Steps to reproduce
_Tell us how to recreate your issue._

Open two terminals. In one terminal, run sudo mongod. In the other terminal, inside the Puente-node-cloud directory, run npm start. Direct your browser to http://localhost:4040/dashboard and the parse dashboard will appear stating "You don't have any apps"

### Expected results
_What did you think would happen?_

I expected to be able to see the application on my local host, in order to make changes.

### Actual results
_What **really** happened?_

The parse dashboard stated "You don't have any apps"

**Comment by hopetambala** [comment]
great issue and something we've also run into

I've looked into this issue from [here](https://github.com/parse-community/parse-dashboard/issues/544),  [here](https://github.com/parse-community/parse-dashboard/issues/762), and [here](https://stackoverflow.com/questions/39668187/parse-dashboard-error-you-dont-have-any-apps). 

the last one seems to be a dud, but i'm currently testing the first two hypotheses. If you solve it, make a pull request and let me know

**Comment by hopetambala** [comment]
@jamccomb92 I've fixed this issue in the new master please check it out! Steps to run the app locally

1. `npm run install`
2. `npm run start-with-dash`

This will run a local version of our parse-server on our machine, it might be even good to start using this for testing now that you have the dashboard
